force-app/main/default/objects/Asset/fields/DeviceId__c.field-meta.xml
<CustomField>
    <fullName>DeviceId__c</fullName>
    <externalId>true</externalId>
    <label>DeviceId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset/fields/Recognition_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Recognition_Threshold__c</fullName>
    <defaultValue>80</defaultValue>
    <label>Recognition Threshold</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Favorite_Music__c.field-meta.xml
<CustomField>
    <fullName>Favorite_Music__c</fullName>
    <label>Favorite Music</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Music_Genres</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Favorite_Sport__c.field-meta.xml
<CustomField>
    <fullName>Favorite_Sport__c</fullName>
    <label>Favorite Sport</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sports</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Office_Floor__c.field-meta.xml
<CustomField>
    <fullName>Office_Floor__c</fullName>
    <label>Office Floor</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MotionDetected__e/MotionDetected__e.object-meta.xml
<CustomObject>
    <description>Fired by a UI button to simulate a motion detector in the elevator lobby. The Raspberry Pi subscribes to this event and kicks off the picture taking cycle in response.</description>
    <label>MotionDetected</label>
    <pluralLabel>MotionDetected</pluralLabel>
</CustomObject>

force-app/main/default/objects/Ride__c/Ride__c.object-meta.xml
<CustomObject>
    <label>Ride</label>
    <nameField>
        <displayFormat>Ride-{00000}</displayFormat>
        <label>Ride Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ride__c/fields/Confidence_1__c.field-meta.xml
<CustomField>
    <fullName>Confidence_1__c</fullName>
    <label>Confidence #1</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Ride__c/fields/Confidence_2__c.field-meta.xml
<CustomField>
    <fullName>Confidence_2__c</fullName>
    <label>Confidence #2</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Ride__c/fields/Confidence_3__c.field-meta.xml
<CustomField>
    <fullName>Confidence_3__c</fullName>
    <label>Confidence #3</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Ride__c/fields/Elevator__c.field-meta.xml
<CustomField>
    <fullName>Elevator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Elevator</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Rides</relationshipLabel>
    <relationshipName>Rides</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ride__c/fields/PictureIdText__c.field-meta.xml
<CustomField>
    <fullName>PictureIdText__c</fullName>
    <label>PictureIdText</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ride__c/fields/Predicted_Rider_1__c.field-meta.xml
<CustomField>
    <fullName>Predicted_Rider_1__c</fullName>
    <label>Predicted Rider #1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ride__c/fields/Predicted_Rider_2__c.field-meta.xml
<CustomField>
    <fullName>Predicted_Rider_2__c</fullName>
    <label>Predicted Rider #2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ride__c/fields/Predicted_Rider_3__c.field-meta.xml
<CustomField>
    <fullName>Predicted_Rider_3__c</fullName>
    <label>Predicted Rider #3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ride__c/fields/Rider__c.field-meta.xml
<CustomField>
    <fullName>Rider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rider</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rides</relationshipLabel>
    <relationshipName>Rides</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rider_Predicted__e/Rider_Predicted__e.object-meta.xml
<CustomObject>
    <description>LegoUtility.getLegoPrediction raises this event when the prediction has been completed.  It is monitored by the orchestration and the elevator panel Lightning control.</description>
    <label>Rider Predicted</label>
    <pluralLabel>Rider Predicted</pluralLabel>
</CustomObject>

force-app/main/default/objects/Rider_Predicted__e/fields/Favorite_Music__c.field-meta.xml
<CustomField>
    <fullName>Favorite_Music__c</fullName>
    <label>Favorite Music</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rider_Predicted__e/fields/Favorite_Sport__c.field-meta.xml
<CustomField>
    <fullName>Favorite_Sport__c</fullName>
    <label>Favorite Sport</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rider_Predicted__e/fields/Known__c.field-meta.xml
<CustomField>
    <fullName>Known__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Known</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rider_Predicted__e/fields/Office_Floor__c.field-meta.xml
<CustomField>
    <fullName>Office_Floor__c</fullName>
    <label>Office Floor</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rider_Predicted__e/fields/RideId__c.field-meta.xml
<CustomField>
    <fullName>RideId__c</fullName>
    <label>RideId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TakeRiderToFloor__e/TakeRiderToFloor__e.object-meta.xml
<CustomObject>
    <description>Raised by orchestration to tell Pi to transport rider.  This differs from MoveElevator in that the Pi should respond with a Ride_Complete event.</description>
    <label>TakeRiderToFloor</label>
    <pluralLabel>TakeRiderToFloor</pluralLabel>
</CustomObject>

force-app/main/default/objects/TakeRiderToFloor__e/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Floor</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Music_Genres.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Country</fullName>
    </customValue>
    <customValue>
        <fullName>Rock</fullName>
    </customValue>
    <customValue>
        <fullName>Hip Hop</fullName>
    </customValue>
    <customValue>
        <fullName>Classic</fullName>
    </customValue>
    <customValue>
        <fullName>Show Tunes</fullName>
    </customValue>
    <masterLabel>Music Genres</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sports.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Football</fullName>
    </customValue>
    <customValue>
        <fullName>Baseball</fullName>
    </customValue>
    <customValue>
        <fullName>Hockey</fullName>
    </customValue>
    <customValue>
        <fullName>Basketball</fullName>
    </customValue>
    <customValue>
        <fullName>Curling</fullName>
    </customValue>
    <masterLabel>Sports</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LegoUtility.cls
global class LegoUtility {
    
    // Invocable version that can be launched from Process Builder
    @InvocableMethod(label='Get Lego Prediction' description='Performs and Einstein Vision prediction')
    global static void getLegoPredictionInvocable (List<LegoPredictionItem> legoPredictionItem) {
        getLegoPredictionAsync(legoPredictionItem[0].rideId);
    }
    
    
    // Asynchronous version needed because Ride will not yet be committed when the invokable
    // is launched in Process Builder.
    @future(callout=true)
    global static void getLegoPredictionAsync(String rideId) {
        getLegoPrediction(rideId);
    }
    
    
    // Synchronous version
    global static void getLegoPrediction(String rideId) {    
        // Get the Ride record
        Ride__c thisRide = [SELECT Id, Name, PictureIdText__c, Elevator__c FROM Ride__c WHERE Id = :rideId];
        
        // Verify there is a string value for the PictureIdText
        if (String.isNotBlank(thisRide.PictureIdText__c)) {
            // Find the ContentVersion (picture file that was created by the Pi)
            ContentVersion cv = [SELECT Id, VersionData, ContentDocumentId FROM ContentVersion WHERE Id = :thisRide.PictureIdText__c];
            Id cdId = cv.ContentDocumentId;
        
            // Find the LegoPeople Einstein model
            EinsteinVision_PredictionService service = new EinsteinVision_PredictionService();
            // Find the first model in the LegoPeople dataset
            EinsteinVision_Dataset[] datasets = service.getDatasets();
            for (EinsteinVision_Dataset dataset : datasets) {
                System.debug('Currentlylooking at dataset ' + dataset.Name);
//                if (dataset.Name.equals('LegoPeople')) {
                if (dataset.Name.equals('LegoPeopleV2')) {
                    EinsteinVision_Model[] models = service.getModels(dataset);
                    EinsteinVision_Model model = models.get(0);
                    System.debug('The modelId being used is ' + model.modelId);
                    
                    // Retrieve the picture content in base64 form
                    String base64 = EncodingUtil.base64Encode(cv.VersionData);
                    
                    // Predict
                    EinsteinVision_PredictionResult result = service.predictBase64(model.modelId, base64, '');
                    System.debug('PredictUrl result ' + result);
                    EinsteinVision_Probability probability = result.probabilities.get(0);
                    
                    // Set the first (most likely) predicted rider, then work your way through three
                    thisRide.Predicted_Rider_1__c = probability.label;
                    thisRide.Confidence_1__c = probability.probability * 100;
                    probability = result.probabilities.get(1);
                    thisRide.Predicted_Rider_2__c = probability.label;
                    thisRide.Confidence_2__c = probability.probability * 100;
                    probability = result.probabilities.get(2);
                    thisRide.Predicted_Rider_3__c = probability.label;
                    thisRide.Confidence_3__c = probability.probability * 100;
                    
                    // Create an event that will be fired, letting the system know we have finished prediction.
                    Asset elevator = [SELECT Id, Recognition_Threshold__c, DeviceId__c FROM Asset WHERE Id= :thisRide.Elevator__c][0];
                    String deviceId = elevator.DeviceId__c;
                    Rider_Predicted__e riderPredicted = new Rider_Predicted__e(
                        Known__c = FALSE, 
                        DeviceId__c = deviceId,
                        RideId__c = thisRide.Id);
                    
                    // If the probability for the first predicted rider is high, link the
                    // contact record to the ride record and populate the event fields.
                    if (thisRide.Confidence_1__c > elevator.Recognition_Threshold__c) {
                        List<Contact> contactMatches = [SELECT Id, Name, FirstName, Favorite_Sport__c, Favorite_Music__c, Office_Floor__c FROM Contact WHERE LastName='Lego' AND FirstName = :thisRide.Predicted_Rider_1__c];
                        if (contactMatches.size() == 1) {
                            thisRide.Rider__c = contactMatches[0].Id;
                            riderPredicted.Known__c = TRUE;
                            riderPredicted.Name__c = contactMatches[0].FirstName;
                            riderPredicted.Favorite_Music__c = contactMatches[0].Favorite_Music__c;
                            riderPredicted.Favorite_Sport__c = contactMatches[0].Favorite_Sport__c;
                            riderPredicted.Office_Floor__c = contactMatches[0].Office_Floor__c;                        
                        }
                    }
                    
                    update thisRide;
                    EventBus.publish(riderPredicted);
                }
            }
            
            // Create a link between the picture (ContentVersion) and the
        	// new Ride record.
            ContentDocumentLink cdl = new ContentDocumentLink();
            cdl.ContentDocumentId = cdId;
            cdl.LinkedEntityId = thisRide.Id;
            cdl.ShareType = 'V';
            cdl.Visibility = 'AllUsers';
            
            insert cdl;
            
            

        }
    }
    
    
    // Controller function for Lightning components
    @AuraEnabled
    public static void goToFloor (Integer floor) {
        TakeRiderToFloor__e takeRiderToFloorEvent = new TakeRiderToFloor__e();
        
        takeRiderToFloorEvent.Floor__c = floor;
        
        EventBus.publish(takeRiderToFloorEvent);
    }
    
    
    @AuraEnabled
    public static void motionDetected () {
        MotionDetected__e motionDetectedEvent = new MotionDetected__e();
        motionDetectedEvent.DeviceId__c = 'ELEVATOR-001';
        
        EventBus.publish(motionDetectedEvent);
    }
    
    
    @AuraEnabled
    public static List<String> getImagesFromRide(Id rideId) {
        System.debug('getImagesFromRide with rideId ' + rideId);
        Ride__c ride = [SELECT Id, Predicted_Rider_1__c, Predicted_Rider_2__c, Predicted_Rider_3__c FROM Ride__c WHERE Id= :rideId][0];
        List<String> returnStrings = new List<String>();
        
        // Get the Id of the attached image.
        Id cdId = [SELECT Id, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId=:rideId][0].ContentDocumentId;
        List<ContentVersion> cv = [SELECT Id FROM ContentVersion WHERE ContentDocumentId =:cdId];
        if (cv.size()>0) {
            returnStrings.add(cv.get(0).Id);
        }
        
        // Find the first Contact and get the picture Id.
        List<Contact> predictedRider = [SELECT Id, Name FROM Contact WHERE FirstName=:ride.Predicted_Rider_1__c AND LastName='Lego'];
        if (predictedRider.size()>0) {
            Id predictedRiderId = predictedRider[0].Id;
            cdId = [SELECT Id, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId=:predictedRiderId].ContentDocumentId;
            cv = [SELECT Id FROM ContentVersion WHERE ContentDocumentId =:cdId];
            if (cv.size()>0) {
                returnStrings.add(cv.get(0).Id);
            }            
        }
        predictedRider = [SELECT Id, Name FROM Contact WHERE FirstName=:ride.Predicted_Rider_2__c AND LastName='Lego'];
        if (predictedRider.size()>0) {
            Id predictedRiderId = predictedRider[0].Id;
            cdId = [SELECT Id, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId=:predictedRiderId].ContentDocumentId;
            cv = [SELECT Id FROM ContentVersion WHERE ContentDocumentId =:cdId];
            if (cv.size()>0) {
                returnStrings.add(cv.get(0).Id);
            }            
        }
        predictedRider = [SELECT Id, Name FROM Contact WHERE FirstName=:ride.Predicted_Rider_3__c AND LastName='Lego'];
        if (predictedRider.size()>0) {
            Id predictedRiderId = predictedRider[0].Id;
            cdId = [SELECT Id, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId=:predictedRiderId].ContentDocumentId;
            cv = [SELECT Id FROM ContentVersion WHERE ContentDocumentId =:cdId];
            if (cv.size()>0) {
                returnStrings.add(cv.get(0).Id);
            }            
        }
        return returnStrings;
    }
    
    @AuraEnabled
    public static List<LegoPrediction> getPredictionsFromRide(Id rideId) {
        System.debug('getPredictionsFromRide with rideId ' + rideId);
        Ride__c ride = [SELECT Id, Predicted_Rider_1__c, Predicted_Rider_2__c, Predicted_Rider_3__c,
                        Confidence_1__c, Confidence_2__c, Confidence_3__c
                        FROM Ride__c WHERE Id= :rideId][0];
        List<LegoPrediction> returnLegoPrediction = new List<LegoPrediction>();
        Id cdId;
        List<ContentVersion> cv;
        
        // Find the first Contact and get the picture Id.
        List<Contact> predictedRider = [SELECT Id, Name FROM Contact WHERE FirstName=:ride.Predicted_Rider_1__c AND LastName='Lego'];
        if (predictedRider.size()>0) {
            Id predictedRiderId = predictedRider[0].Id;
            cdId = [SELECT Id, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId=:predictedRiderId].ContentDocumentId;
            cv = [SELECT Id FROM ContentVersion WHERE ContentDocumentId =:cdId];
            if (cv.size()>0) {
                LegoPrediction prediction = new LegoPrediction(
                    ride.Predicted_Rider_1__c, 
                    ride.Confidence_1__c.setScale(2, RoundingMode.HALF_UP),
                    cv.get(0).Id);
                returnLegoPrediction.add(prediction);
            }            
        }
        predictedRider = [SELECT Id, Name FROM Contact WHERE FirstName=:ride.Predicted_Rider_2__c AND LastName='Lego'];
        if (predictedRider.size()>0) {
            Id predictedRiderId = predictedRider[0].Id;
            cdId = [SELECT Id, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId=:predictedRiderId].ContentDocumentId;
            cv = [SELECT Id FROM ContentVersion WHERE ContentDocumentId =:cdId];
            if (cv.size()>0) {
                LegoPrediction prediction = new LegoPrediction(
                    ride.Predicted_Rider_2__c, 
                    ride.Confidence_2__c.setScale(2, RoundingMode.HALF_UP),
                    cv.get(0).Id);
                returnLegoPrediction.add(prediction);
            }            
        }
        predictedRider = [SELECT Id, Name FROM Contact WHERE FirstName=:ride.Predicted_Rider_3__c AND LastName='Lego'];
        if (predictedRider.size()>0) {
            Id predictedRiderId = predictedRider[0].Id;
            cdId = [SELECT Id, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId=:predictedRiderId].ContentDocumentId;
            cv = [SELECT Id FROM ContentVersion WHERE ContentDocumentId =:cdId];
            if (cv.size()>0) {
                LegoPrediction prediction = new LegoPrediction(
                    ride.Predicted_Rider_3__c, 
                    ride.Confidence_3__c.setScale(2, RoundingMode.HALF_UP),
                    cv.get(0).Id);
                returnLegoPrediction.add(prediction);
            }            
        }
        return returnLegoPrediction;
    }

    @AuraEnabled
    public static String getSessionId() {
        return UserInfo.getSessionId();
    }
    
}